---

- name: install audio tools
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - libasound2
    - libasound2-plugin-equal
    - alsa-utils
    - alsa-oss


