---

- name: install input device config tools
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - xinput
    - xclip

- name: set up xorg.conf.d directory
  when: ansible_os_family == "Debian"
  become: yes
  file: dest="/etc/X11/xorg.conf.d/" state="directory"

- name: create input config
  become: yes
  when: ansible_os_family == "Debian"
  copy:
    src: 10-keyboard.conf
    dest: /etc/X11/xorg.conf.d/10-keyboard.conf
