- name: install programming utilities
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - bear
    - clang-6.0
    - libclang-6.0-dev
    - cmake
    - rtags
    - lua5.3
    - global
    - haskell-stack 
