- name: install general system utilities
  become: yes
  when: ansible_os_family == "Debian"
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - texlive-full
    - gnome-screenshot
    - vlc
    - xbindkeys
    - gparted
    - haveged
    - inkscape
    - udevil
    - feh
    
