---

- name: install x11
  when: ansible_os_family == "Debian"
  become: yes
  apt: name="xorg" state=latest

- name: install intel drivers
  when: gpu is defined and gpu == "intel" and ansible_os_family == "Debian"
  become: yes
  apt: name="{{item}}" state=latest
  with_items:
    - mesa-utils    
    - xserver-xorg-video-intel

- name: set up xorg.conf.d directory
  when: ansible_os_family == "Debian"
  become: yes
  file: dest="/etc/X11/xorg.conf.d/" state="directory"

- name: create GPU driver section
  become: yes
  when: gpu is defined and gpu == "intel"
  copy:
    src: 20-intel.conf
    dest: /etc/X11/xorg.conf.d/20-intel.conf

- name: install x11 packages
  become: yes
  when: ansible_os_family == "Debian"
  apt: name="{{item}}" state=latest
  with_items:
    - rofi
    - xmonad
    - xmobar
    - stalonetray
    - compton
    - unclutter
    - slock
    - xfonts-terminus
    - fonts-hack-ttf
    - sakura
    - dunst
    - libnotify-bin
    - gnuplot
    - xinit
    - x11-xserver-utils

